config/routes.rb
Rails.application.routes.draw do

  resources :skills, :vacancies, :candidates do
    get "delete"
  end
  resources :skill_items, only: [:create, :update, :destroy]
  root to: "vacancies#index"

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	has_and_belongs_to_many :vacancies
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :skill_items, dependent: :delete_all
end

app/models/skill_item.rb
class SkillItem < ActiveRecord::Base
  belongs_to :skill
  belongs_to :vacancy
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  has_many :skill_items, dependent: :destroy
  has_and_belongs_to_many :candidates
  before_destroy :delete_skills, prepend: true

  private 
  def delete_skills
  	skill_items = self.skill_items
  	skill_items.each do |item|
  		Skill.find(item.skill_id).destroy
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_vacancy

  def current_vacancy
  	if !session[:vacancy_id].nil?
  		Vacancy.find(session[:vacancy_id])
  	else
  		Vacancy.new
  	end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  respond_to :html, :js

  def new
  	@candidate = Candidate.new
  	@vacancies = Vacancy.all.map {|v| [v.title, v.id]}
  end

  def create
  	@candidate = Candidate.create(candidate_params)
  	@candidate.vacancies << Vacancy.find(params[:vacancy_id])
    if @candidate.save
      redirect_to candidates_url
    else
      render :new
    end
  end

  def index
  	@candidates = Candidate.all
  end

  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy
    redirect_to candidates_url
  end

  private 
  def candidate_params
  	params.require(:candidate).permit(:full_name, :address)
  end
end

app/controllers/skill_items_controller.rb
class SkillItemsController < ApplicationController
  def create
  end

  def update
  end

  def destroy
  end

  private 

  def skill_items_params
  	params.require(:skill_item).permit(:vacancy_id, :skill_id, :actual_level)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  respond_to :html, :js
  before_action :add_levels, only: [:create, :update, :new, :edit]

  def index
    @skills = get_vacancy_skills
  end

  def show
  	@skill = Skill.find(params[:id])
  end

  def create
  	@skill = Skill.create(skill_params)
    vacancy_id = session[:vacancy_id]
    @skill_item = SkillItem.create!(skill_id: @skill.id, vacancy_id: vacancy_id)
    @skills = get_vacancy_skills
  end

  def new
  	@skill = Skill.new
    @skill_item = SkillItem.new
  	@title = "New skill"
  end

  def edit
  	@skill = Skill.find(params[:id])
  	@title = "Editing #{@skill.name}"
    @skills = get_vacancy_skills
  end

  def update
  	@skill = Skill.find(params[:id])
  	@skill.update_attributes(skill_params)
    @skills = get_vacancy_skills
  end

  def delete
  	@skill = Skill.find(params[:skill_id])
  end

  def destroy
  	@skills = get_vacancy_skills
  	@skill = Skill.find(params[:id])
  	@skill.destroy
  end

  private 
  	def skill_params
  		params.require(:skill).permit(:name, :required_level, :actual_level)
  	end

  	def add_levels
  		@levels = ['Limited knowledge', 'Working knowledge', 'Extensive knowledge', 'Expert']
  	end

    def get_vacancy_skills
    if !session[:vacancy_id].nil?  
      skill_items = Vacancy.find(session[:vacancy_id]).skill_items
      vacancy_skills = []
      skill_items.each do |item|
        vacancy_skills << Skill.find(item.skill_id)
      end
    else
      vacancy_skills = Skill.all
    end
    vacancy_skills
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  respond_to :html, :js

  def index
  	@vacancies = Vacancy.all
  end

  def show
  	@vacancy = Vacancy.find(params[:id])
  	skill_items = @vacancy.skill_items
  	@vacancy_skills = get_vacancy_skills
  end

  def new
  	@vacancy = Vacancy.new
  	@title = "New Vacancy"
  end

  def create
  	@vacancies = Vacancy.all
  	@vacancy = Vacancy.create(vacancy_params)
  end

  def delete
  	@vacancy = Vacancy.find(params[:vacancy_id])
  end

  def destroy
  	@vacancies = Vacancy.all
  	@vacancy = Vacancy.find(params[:id])
  	@vacancy.destroy
  end

  def edit
  	@vacancy = Vacancy.find(params[:id])
    session[:vacancy_id] = @vacancy.id
  	@title = "Editing #{@vacancy.title}"
    @skills = get_vacancy_skills
  end

  def update
  	@vacancies = Vacancy.all
  	@vacancy = Vacancy.find(params[:id])
    @skills = get_vacancy_skills
  end

  private
  def vacancy_params
  	params.require(:vacancy).permit(:title, :description)
  end

  def get_vacancy_skills
  	skill_items = @vacancy.skill_items
  	vacancy_skills = []
  	skill_items.each do |item|
  		vacancy_skills << Skill.find(item.skill_id)
  	end
  	vacancy_skills
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/skill_items_helper.rb
module SkillItemsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/candidates/_index.html.erb
<% @candidates.each do |candidate| %>
	<tr>
		<td><%= candidate.full_name %></td>
		<td><%= candidate.address %></td>
		<td><%= candidate.vacancies.first.title%></td>
		<td><%= link_to "Edit Skills", controller: "vacancies", action: "edit", id: candidate.vacancies.first.id %></td>
		<td><%= link_to "Delete", candidate, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
	</tr>
<% end %>

app/views/candidates/create.html.erb
<h1>Candidates#create</h1>
<p>Find me in app/views/candidates/create.html.erb</p>

app/views/candidates/index.html.erb
<div class="container">
	<div class="new-candidate">
		
	</div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Full Name</th>
				<th>Address</th>
				<th>Vacancy</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody class="candidate-index">
			<%= render "index" %>
		</tbody>
	</table>
	<div class="well">
		<%= link_to "New Candidate", new_candidate_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/candidates/new.html.erb
<%= form_for @candidate do |f| %>
	<div class="control-group">
          <%= f.label :full_name, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :full_name %>
          </div>
    </div>
    <div class="control-group">
          <%= f.label :address, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :address %>
          </div>
    </div>
    <br/>
    <div class="control-group">
      <%= label :vacancy_id, "Select vacancy" %>
      <div class="controls">
        <%= select_tag(:vacancy_id, options_for_select(@vacancies)) %>
      </div>
    </div>
    <br/>
    <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResBuilder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/skill_items/create.html.erb
<h1>SkillItems#create</h1>
<p>Find me in app/views/skill_items/create.html.erb</p>

app/views/skill_items/destroy.html.erb
<h1>SkillItems#destroy</h1>
<p>Find me in app/views/skill_items/destroy.html.erb</p>

app/views/skill_items/update.html.erb
<h1>SkillItems#update</h1>
<p>Find me in app/views/skill_items/update.html.erb</p>

app/views/skills/_delete.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h3>Delete skill</h3>
		</div>
		<div class="modal-body">
			<ul class="errors"></ul>
			Are you sure you wish to delete <b><%= @skill.name %></b>?
		</div>
		<div class="modal-footer">
			<%= link_to "Yes, Delete This Skill", skill_path(@skill), method: :delete, remote: true, class: "btn btn-danger" %>
			<%= link_to "No, Please Don't", "#", class: "btn", data: {dismiss: "modal"} %>
		</div>
	</div>
</div>	

app/views/skills/_edit.html.erb
<%= render "skills/form" %>

app/views/skills/_form.html.erb
<%= form_for @skill, remote: true, html: {class: "form-horizontal", style: "display:inline;"} do |f| %>
	<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3><%= @title %></h3>
      </div>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="control-group">
          <%= f.label :name, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :required_level, class: "control-label" %>
          <div class="controls">
            <%= f.select :required_level, @levels %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary"%>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    </div>
  </div>
<% end %>

app/views/skills/_index.html.erb
<% @skills.each do |skill| %>
	<tr>
		<td><%= skill.name %></td>
		<td><%= skill.required_level %></td>
		<td><%= link_to "Edit", edit_skill_path(skill), remote: true, class: "btn" %></td>
		<td><%= link_to "Delete", skill_delete_path(skill), remote: true, class: "btn btn-danger"%></td>
	</tr>
<% end %>

app/views/skills/_new.html.erb
<%= render "skills/form" %>

app/views/skills/_save.js.erb
$("ul.errors").html("")
<% if @skill.errors.any? %>
	<% @skill.errors.full_messages.each do |message| %>
		$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	<% end %>
<% else %>
	$(".skill-index").html("<%= j (render 'skills/index' ) %>")
	$("#skill-modal").modal("hide")
<% end %>

app/views/skills/create.js.erb
<%= render "skills/save" %>

app/views/skills/delete.js.erb
$("#skill-modal").html("<%= j (render 'skills/delete') %>")
$("#skill-modal").modal("show")

app/views/skills/destroy.js.erb
<%= render "skills/save" %>

app/views/skills/edit.js.erb
$("#skill-modal").html("<%= j (render 'skills/edit') %>")
$("#skill-modal").modal("show")

app/views/skills/index.html.erb
<div class="container">
	<div class="new-skill">
		
	</div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Required level</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody class="skill-index">
			<%= render "skills/index" %>
		</tbody>
	</table>
	<div class="well">
		<%= link_to "New Skill", new_skill_path, remote: true, class: "btn btn-primary" %>
	</div>
</div>
<div id="skill-modal" class="modal fade">
	
</div>

app/views/skills/new.js.erb
$("#skill-modal").html("<%= j (render 'skills/new') %>")
$("#skill-modal").modal("show")

app/views/skills/update.js.erb
<%= render "save" %>

app/views/vacancies/_add_skills.html.erb
<h1><%= @title %></h1>
<h4>Description: <b><%= @vacancy.description %></b></h4>
<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Required level</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody class="skill-index">
			<%= render "skills/index" %>
		</tbody>
	</table>
<div class="well">
		<%= link_to "New Skill", new_skill_path, remote: true, class: "btn btn-primary" %>
		<%= link_to "Back", candidates_path, class: "btn btn-primary"%>
</div>
<div id="skill-modal" class="modal fade">
	
</div>

app/views/vacancies/_delete.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h3>Delete vacancy</h3>
		</div>
		<div class="modal-body">
			<ul class="errors"></ul>
			Are you sure you wish to delete <b><%= @vacancy.title %></b>?
		</div>
		<div class="modal-footer">
			<%= link_to "Yes, Delete This Vacancy", vacancy_path(@vacancy), method: :delete, remote: true, class: "btn btn-danger" %>
			<%= link_to "No, Please Don't", "#", class: "btn", data: {dismiss: "modal"} %>
		</div>
	</div>
</div>	

app/views/vacancies/_form.html.erb
<%= form_for @vacancy, remote: true, html: {class: "form-horizontal", style: "display:inline;"} do |f| %>
	<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3><%= @title %></h3>
      </div>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="control-group">
          <%= f.label :title, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :title %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :description, class: "control-label" %>
          <div class="controls">
            <%= f.text_area :description %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary"%>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    </div>
  </div>
<% end %>

app/views/vacancies/_index.html.erb
<% @vacancies.each do |vacancy| %>
	<tr>
		<td><%= link_to vacancy.title, vacancy %></td>
		<td><%= vacancy.description %></td>
		<td><%= link_to "Add Skills", edit_vacancy_path(vacancy), class: "btn" %></td>
		<td><%= link_to "Delete", vacancy_delete_path(vacancy), remote: true, class: "btn btn-danger"%></td>
	</tr>
<% end %>

app/views/vacancies/_new.html.erb
<%= render "form" %>

app/views/vacancies/_save.js.erb
$("ul.errors").html("")
<% if @vacancy.errors.any? %>
	<% @vacancy.errors.full_messages.each do |message| %>
		$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	<% end %>
<% else %>
	$(".vacancy-index").html("<%= j (render 'index' ) %>")
	$("#vacancy-modal").modal("hide")
<% end %>

app/views/vacancies/_skill_list.html.erb
<h3><%= @vacancy.title %></h3><br />
<h4><%= @vacancy.description %></h4>
<p>Skills: </p>
<ul>
	<% @vacancy_skills.each do |skill| %>
		<li><%= skill.name %> - <%= skill.required_level %></li>
	<% end %>
</ul>

app/views/vacancies/create.js.erb
<%= render "save" %>

app/views/vacancies/delete.js.erb
$("#vacancy-modal").html("<%= j (render 'delete') %>")
$("#vacancy-modal").modal("show")

app/views/vacancies/destroy.js.erb
<%= render "save" %>

app/views/vacancies/edit.html.erb
<%= render "add_skills" %>

app/views/vacancies/index.html.erb
<div class="container">
	<div class="new-vacancy">
		
	</div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody class="vacancy-index">
			<%= render "index" %>
		</tbody>
	</table>
	<div class="well">
		<%= link_to "New Vacancy", new_vacancy_path , remote: true, class: "btn btn-primary" %>
	</div>
</div>
<div id="vacancy-modal" class="modal fade">
	
</div>

app/views/vacancies/new.js.erb
$("#vacancy-modal").html("<%= j (render 'new') %>")
$("#vacancy-modal").modal("show")

app/views/vacancies/show.html.erb
<div class="skill-list">
	<%= render "skill_list" %>
</div>